export enum IconsEnum {
  STAR = 'star',
  CAKE = 'cake',
  DECK = 'deck',
  SMILE = 'emoji_emotions',
  CUP = 'emoji_events',
  FLAG = 'emoji_flags',
  BEVERAGE = 'emoji_food_beverage',
  BEE = 'emoji_nature',
  BULB = 'emoji_objects',
  DISSATISFIED = 'sentiment_dissatisfied',
  SATISFIED = 'sentiment_satisfied',
  VERY_DISSATISFIED = 'sentiment_very_dissatisfied',
  NIGHT = 'nights_stay',
  EARTH = 'public',
  SCHOOL = 'school',
  ESPORT = 'sports_esports',
  LEAF = 'eco',
  EXPLORE = 'explore',
  HEART = 'favorite',
  HOME = 'home',
  GAVEL = 'gavel',
  LOCK = 'https',
  HOURGLASS = 'hourglass_full',
  ERROR = 'error',
  WARNING= 'warning',
  CIRCLE = 'fiber_manual_record',
  EYE = 'visibility',
  RADAR = 'track_changes',

}
